origin_hostname = "terra-demo-dev.akamaized.net"
cp_code         = 9999999
property_name   = "terra-demo-dev"
contract_id     = "ctr_C-XXXXXX"
group_id        = "grp_123456"
hostname        = "terra-demo-dev.akamaized.net"
edge_hostname   = "terra-demo-dev.akamaized.net"
env = "dev"
property_version_notes = "Terraform update for dev environment"
activate_latest_on_staging = false
activate_latest_on_production = false
