origin_hostname = "terra-demo-prod.akamaized.net"
cp_code         = 9999999
property_name   = "terra-demo-prod"
contract_id     = "ctr_C-1ED34DY"
group_id        = "grp_123456"
hostname        = "terra-demo-prod.akamaized.net"
edge_hostname   = "terra-demo-prod.akamaized.net"
env = "prod"
property_version_notes = "Terraform update for prod environment"
activate_latest_on_staging = false
activate_latest_on_production = false
